# Build and push artifacts
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install protobuf
      run: sudo apt-get install -y protobuf-compiler
    - name: CMake generate
      env:
        ARTIFACT_NAME: ppc2cpp-${{ runner.os }}
      run: |
        cmake -B build \
          -DCMAKE_INSTALL_PREFIX=$ARTIFACT_NAME \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=OFF \
          -DProtobuf_PROTOC_EXECUTABLE="$(which protoc)" \
          -DProtobuf_LIBRARY="$(pkg-config --libs protobuf)"
    - name: Build
      run: cmake --build build --target install -j
    
    - uses: actions/upload-artifact@v3
      if: github.ref == 'refs/heads/main' && github.repository == 'em-eight/ppc2cpp'
      with:
        name: ppc2cpp-${{ runner.os }}
        path: ppc2cpp-${{ runner.os }}