name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: CMake configure
        run: cmake -B build
      - name: CMake build
        run: cmake --build build -j
